
// This file has been generated by the GUI designer. Do not modify.
namespace Serpis.Ad
{
	public partial class BotonDelete
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label2;
		private global::Gtk.Entry cajaBorrar;
		private global::Gtk.Button eliminar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Serpis.Ad.BotonDelete
			this.Name = "Serpis.Ad.BotonDelete";
			this.Title = global::Mono.Unix.Catalog.GetString ("Borrar campo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Serpis.Ad.BotonDelete.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Introduce el valor a borrar");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.cajaBorrar = new global::Gtk.Entry ();
			this.cajaBorrar.CanFocus = true;
			this.cajaBorrar.Name = "cajaBorrar";
			this.cajaBorrar.IsEditable = true;
			this.cajaBorrar.InvisibleChar = '•';
			this.vbox3.Add (this.cajaBorrar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.cajaBorrar]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.eliminar = new global::Gtk.Button ();
			this.eliminar.CanFocus = true;
			this.eliminar.Name = "eliminar";
			this.eliminar.UseUnderline = true;
			this.eliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.vbox3.Add (this.eliminar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eliminar]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
