
// This file has been generated by the GUI designer. Do not modify.
namespace Serpis.Ad
{
	public partial class BotonAdd
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Entry caja;
		private global::Gtk.Button aceptar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Serpis.Ad.BotonAdd
			this.Name = "Serpis.Ad.BotonAdd";
			this.Title = global::Mono.Unix.Catalog.GetString ("Añadir");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Serpis.Ad.BotonAdd.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Introduce el nuevo valor");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.caja = new global::Gtk.Entry ();
			this.caja.CanFocus = true;
			this.caja.Name = "caja";
			this.caja.IsEditable = true;
			this.caja.InvisibleChar = '•';
			this.vbox1.Add (this.caja);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.caja]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.aceptar = new global::Gtk.Button ();
			this.aceptar.CanFocus = true;
			this.aceptar.Name = "aceptar";
			this.aceptar.UseUnderline = true;
			this.aceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.vbox1.Add (this.aceptar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aceptar]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
